"""baseline schema

Revision ID: 755e3b02b3f9
Revises: 
Create Date: 2026-07-09 11:32:03.176314

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.db

# revision identifiers, used by Alembic.
revision: str = '755e3b02b3f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.UTCDateTime(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('target', sa.String(length=400), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_ts'), 'audit_logs', ['ts'], unique=False)
    op.create_table('claude_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.UTCDateTime(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claude_usage_run_id'), 'claude_usage', ['run_id'], unique=False)
    op.create_index(op.f('ix_claude_usage_ts'), 'claude_usage', ['ts'], unique=False)
    op.create_table('project_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('project_key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('repo', sa.String(length=300), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('needs_refresh', sa.Boolean(), nullable=False),
    sa.Column('last_indexed', app.db.UTCDateTime(), nullable=True),
    sa.Column('knowledge', sa.JSON(), nullable=False),
    sa.Column('doc_path', sa.String(length=600), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_knowledge_key'), 'project_knowledge', ['key'], unique=True)
    op.create_index(op.f('ix_project_knowledge_project_key'), 'project_knowledge', ['project_key'], unique=False)
    op.create_index(op.f('ix_project_knowledge_status'), 'project_knowledge', ['status'], unique=False)
    op.create_table('provider_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secrets', sa.JSON(), nullable=False),
    sa.Column('last_sync', app.db.UTCDateTime(), nullable=True),
    sa.Column('last_tested_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_connections_kind'), 'provider_connections', ['kind'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secrets', sa.JSON(), nullable=False),
    sa.Column('last_sync', app.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_kind'), 'providers', ['kind'], unique=True)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_label', sa.String(length=120), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('browser', sa.String(length=32), nullable=False),
    sa.Column('env', sa.String(length=32), nullable=False),
    sa.Column('workers', sa.Integer(), nullable=False),
    sa.Column('retry_policy', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('failed_stage', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_code'), 'runs', ['code'], unique=True)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('env', sa.String(length=32), nullable=False),
    sa.Column('browser', sa.String(length=32), nullable=False),
    sa.Column('workers', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_run_id'), 'executions', ['run_id'], unique=False)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_table('linked_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('ticket_external_id', sa.String(length=64), nullable=False),
    sa.Column('provider_kind', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('linked', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_test_cases_ticket_external_id'), 'linked_test_cases', ['ticket_external_id'], unique=False)
    op.create_table('project_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('work_item_connection_id', sa.Integer(), nullable=True),
    sa.Column('repository_connection_id', sa.Integer(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('repos', sa.JSON(), nullable=False),
    sa.Column('local_repo_path', sa.String(length=600), nullable=False),
    sa.Column('repo_url', sa.String(length=600), nullable=False),
    sa.Column('environments', sa.JSON(), nullable=False),
    sa.Column('test_accounts', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('manual_auth', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_connection_id'], ['provider_connections.id'], ),
    sa.ForeignKeyConstraint(['work_item_connection_id'], ['provider_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_config_key'), 'project_config', ['key'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_kind', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['provider_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_external_id'), 'projects', ['external_id'], unique=False)
    op.create_index(op.f('ix_projects_provider_kind'), 'projects', ['provider_kind'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('overall_result', sa.String(length=16), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_run_id'), 'reports', ['run_id'], unique=False)
    op.create_table('run_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('ticket_external_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('gen_status', sa.String(length=16), nullable=False),
    sa.Column('repo', sa.String(length=300), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_tickets_run_id'), 'run_tickets', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_tickets_ticket_external_id'), 'run_tickets', ['ticket_external_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ticket_external_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('precondition', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('test_type', sa.String(length=48), nullable=False),
    sa.Column('automation', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.String(length=16), nullable=False),
    sa.Column('approval', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_approval'), 'test_cases', ['approval'], unique=False)
    op.create_index(op.f('ix_test_cases_run_id'), 'test_cases', ['run_id'], unique=False)
    op.create_index(op.f('ix_test_cases_ticket_external_id'), 'test_cases', ['ticket_external_id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ticket_external_id', sa.String(length=64), nullable=False),
    sa.Column('provider_kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_status', sa.String(length=48), nullable=False),
    sa.Column('external_comment_id', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_run_id'), 'ticket_comments', ['run_id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_status'), 'ticket_comments', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_external_id'), 'ticket_comments', ['ticket_external_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('provider_kind', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('work_item_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assignee', sa.String(length=120), nullable=False),
    sa.Column('sprint', sa.String(length=120), nullable=False),
    sa.Column('area_path', sa.String(length=300), nullable=False),
    sa.Column('epic', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('linked_prs', sa.JSON(), nullable=False),
    sa.Column('synced_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['provider_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_connection_id'), 'tickets', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tickets_external_id'), 'tickets', ['external_id'], unique=False)
    op.create_index(op.f('ix_tickets_project_id'), 'tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tickets_provider_kind'), 'tickets', ['provider_kind'], unique=False)
    op.create_table('automation_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('heal_report', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=False),
    sa.Column('gate_report', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_specs_status'), 'automation_specs', ['status'], unique=False)
    op.create_index(op.f('ix_automation_specs_test_case_id'), 'automation_specs', ['test_case_id'], unique=True)
    op.create_table('execution_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('ticket_external_id', sa.String(length=64), nullable=False),
    sa.Column('case_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_class', sa.String(length=24), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('console_logs', sa.JSON(), nullable=False),
    sa.Column('network_logs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_results_execution_id'), 'execution_results', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_results_status'), 'execution_results', ['status'], unique=False)
    op.create_index(op.f('ix_execution_results_test_case_id'), 'execution_results', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_execution_results_ticket_external_id'), 'execution_results', ['ticket_external_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('annotated', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['execution_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_kind'), 'evidence', ['kind'], unique=False)
    op.create_index(op.f('ix_evidence_result_id'), 'evidence', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_result_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_kind'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_execution_results_ticket_external_id'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_test_case_id'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_status'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_execution_id'), table_name='execution_results')
    op.drop_table('execution_results')
    op.drop_index(op.f('ix_automation_specs_test_case_id'), table_name='automation_specs')
    op.drop_index(op.f('ix_automation_specs_status'), table_name='automation_specs')
    op.drop_table('automation_specs')
    op.drop_index(op.f('ix_tickets_provider_kind'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_project_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_external_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_connection_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ticket_comments_ticket_external_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_status'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_run_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_test_cases_ticket_external_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_run_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_approval'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_run_tickets_ticket_external_id'), table_name='run_tickets')
    op.drop_index(op.f('ix_run_tickets_run_id'), table_name='run_tickets')
    op.drop_table('run_tickets')
    op.drop_index(op.f('ix_reports_run_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_projects_provider_kind'), table_name='projects')
    op.drop_index(op.f('ix_projects_external_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_config_key'), table_name='project_config')
    op.drop_table('project_config')
    op.drop_index(op.f('ix_linked_test_cases_ticket_external_id'), table_name='linked_test_cases')
    op.drop_table('linked_test_cases')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_index(op.f('ix_executions_run_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_code'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_providers_kind'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_provider_connections_kind'), table_name='provider_connections')
    op.drop_table('provider_connections')
    op.drop_index(op.f('ix_project_knowledge_status'), table_name='project_knowledge')
    op.drop_index(op.f('ix_project_knowledge_project_key'), table_name='project_knowledge')
    op.drop_index(op.f('ix_project_knowledge_key'), table_name='project_knowledge')
    op.drop_table('project_knowledge')
    op.drop_index(op.f('ix_claude_usage_ts'), table_name='claude_usage')
    op.drop_index(op.f('ix_claude_usage_run_id'), table_name='claude_usage')
    op.drop_table('claude_usage')
    op.drop_index(op.f('ix_audit_logs_ts'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
