/**
 * E2E spec — generated by automation-generator
 * ---------------------------------------------------------------------------
 * Source ticket : <ADO/Jira ID>
 * Coverage area : <feature / screen>
 * Traceability  : each test() below is tagged with its source Test Case ID.
 *
 *   Test Case ID   →  test() title
 *   TC-<id>-001    →  "<happy path title>"
 *   TC-<id>-002    →  "<negative path title>"
 *
 * Reused assets (from Project Knowledge Base — knowledge.md):
 *   - Page Objects : LoginPage, <FeaturePage>
 *   - Fixtures     : authenticated `test` (storageState) — see fixtures/auth.ts
 *   - Helpers      : <dataBuilder, apiSetup, ...>
 *
 * New Page Object methods added (if any):
 *   - <FeaturePage>.<newMethod>(...)  // reason: not previously covered
 * ---------------------------------------------------------------------------
 */

// Prefer the project's existing custom `test` fixture (auth/storageState) over the raw import.
// import { test, expect } from '../fixtures';           // <-- reuse project fixture if it exists
import { test, expect } from '@playwright/test';

// Reuse existing Page Objects — do NOT re-declare selectors inline.
import { LoginPage } from '../pages/LoginPage';
import { FeaturePage } from '../pages/FeaturePage';

test.describe('<Feature> — <ticket ID>', () => {
  let feature: FeaturePage;

  test.beforeEach(async ({ page }) => {
    // Auth: reuse the KB-documented strategy. If a storageState/auth fixture exists,
    // prefer it and delete this manual login. Manual login shown only as a fallback.
    const login = new LoginPage(page);
    await login.goto();
    await login.login(process.env.QA_USER!, process.env.QA_PASS!);

    feature = new FeaturePage(page);
    await feature.goto();
  });

  /**
   * TC-<id>-001 — Happy path: <objective>
   * Preconditions: <from test case>
   */
  test('TC-<id>-001 <happy path title>', async ({ page }) => {
    // --- Arrange --- (test data / preconditions)
    const invoiceId = '<seeded-id>';

    // --- Act --- (map each test step to a Page Object action)
    await feature.openItem(invoiceId);
    await feature.submit();

    // --- Assert --- (one web-first assertion per Expected Result)
    await expect(feature.confirmationBanner).toBeVisible();
    await expect(feature.statusBadge).toHaveText('Completed');
  });

  /**
   * TC-<id>-002 — Negative path: <invalid input / permission / boundary>
   */
  test('TC-<id>-002 <negative path title>', async () => {
    // --- Arrange ---
    // --- Act ---
    await feature.submit(); // e.g. submit with missing required field

    // --- Assert --- expected validation error
    await expect(feature.validationError).toContainText('<expected message>');
  });
});
